[tool.poetry]
name = "build"
version = "0.1.0"
description = ""
authors = ["Aled"]

[tool.poetry.dependencies]
python = "3.8.12"
opencv-python = "^4.6.0"
tqdm = "^4.64.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
